#index:
#    path: /
#    controller: App\Controller\DefaultController::index
APIFetchingHistory:
    path: /api/geolocation/history
    controller: App\Controller\APIController:fetchHistory

APIMap:
    path: /api/geolocation/{postcode}
    controller: App\Controller\APIController:translate
